$old = (docker container ls -q --filter "name=kudulite")

if ($old) {
    docker container rm -f $old
}

docker run --name kudulite --publish 8080:80 -e "CONTAINER_ENCRYPTION_KEY=MDEyMzQ1Njc4OUFCQ0RFRjAxMjM0NTY3ODlBQkNERUY=" -e "WEBSITE_AUTH_ENCRYPTION_KEY=E782F47415EEC076F8087729FB30CF1CA1482610C2FA985E4F22531225722205" -e "WEBSITE_SITE_NAME=azclidemo" -e "WEBSITE_HOSTNAME=azclidemo.azurewebsites.com" -e "APPSETTING_FUNCTIONS_WORKER_RUNTIME=python" -e "APPSETTING_FUNCTIONS_EXTENSION_VERSION=~2" -e "APPSETTING_FRAMEWORK=PYTHON" -e "APPSETTING_FRAMEWORK_VERSION=3.6" -e "APPSETTING_ENABLE_ORYX_BUILD=true" -e "APPSETTING_SCM_DO_BUILD_DURING_DEPLOYMENT=true" -e "ENABLE_ORYX_BUILD=true" -e "SCM_DO_BUILD_DURING_DEPLOYMENT=true" $args[0]